version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/mainpage"
    target-branch: "dev"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "bun"
    directory: "/docs"
    target-branch: "dev"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "uv"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
